import json
from sqlalchemy.orm import Session
from models.assessment import Scale

PHQ9 = {
    "name": "PHQ-9 抑郁症筛查量表",
    "description": "过去两周内，以下问题困扰你的频率是？用于抑郁症初步筛查，总分27分。0-4=无抑郁，5-9=轻度，10-14=中度，15-19=中重度，20-27=重度",
    "questions": [
        {"id": 1, "text": "做事时提不起劲或没有兴趣"},
        {"id": 2, "text": "感到心情低落、沮丧或绝望"},
        {"id": 3, "text": "入睡困难、睡不安稳或睡眠过多"},
        {"id": 4, "text": "感觉疲倦或没有活力"},
        {"id": 5, "text": "食欲不振或吃太多"},
        {"id": 6, "text": "觉得自己很糟，或感到失败，或让自己或家人失望"},
        {"id": 7, "text": "对事物专注有困难，如阅读或看电视"},
        {"id": 8, "text": "动作或说话速度缓慢到别人可察觉，或比平日更烦躁、坐立不安"},
        {"id": 9, "text": "有不如死掉或用某种方式伤害自己的念头"},
    ],
    "options": [
        {"value": 0, "label": "完全不会"},
        {"value": 1, "label": "好几天"},
        {"value": 2, "label": "一半以上天数"},
        {"value": 3, "label": "几乎每天"},
    ],
    "scoring": {
        "ranges": [
            {"min": 0, "max": 4, "level": "none", "label": "无抑郁症状"},
            {"min": 5, "max": 9, "level": "yellow", "label": "轻度抑郁"},
            {"min": 10, "max": 14, "level": "yellow", "label": "中度抑郁"},
            {"min": 15, "max": 19, "level": "red", "label": "中重度抑郁"},
            {"min": 20, "max": 27, "level": "red", "label": "重度抑郁"},
        ],
        "high_risk_item": 9,
    },
}

GAD7 = {
    "name": "GAD-7 焦虑症筛查量表",
    "description": "过去两周内，以下问题困扰你的频率是？用于焦虑症初步筛查，总分21分。0-4=无焦虑，5-9=轻度，10-14=中度，15-21=重度",
    "questions": [
        {"id": 1, "text": "感觉紧张、焦虑或急切"},
        {"id": 2, "text": "无法停止或控制担忧"},
        {"id": 3, "text": "对各种各样的事情担忧过多"},
        {"id": 4, "text": "很难放松下来"},
        {"id": 5, "text": "由于不安而无法静坐"},
        {"id": 6, "text": "变得容易烦恼或急躁"},
        {"id": 7, "text": "感到似乎将有可怕的事情发生而害怕"},
    ],
    "options": [
        {"value": 0, "label": "完全不会"},
        {"value": 1, "label": "好几天"},
        {"value": 2, "label": "一半以上天数"},
        {"value": 3, "label": "几乎每天"},
    ],
    "scoring": {
        "ranges": [
            {"min": 0, "max": 4, "level": "none", "label": "无焦虑症状"},
            {"min": 5, "max": 9, "level": "yellow", "label": "轻度焦虑"},
            {"min": 10, "max": 14, "level": "yellow", "label": "中度焦虑"},
            {"min": 15, "max": 21, "level": "red", "label": "重度焦虑"},
        ],
    },
}

SCL90 = {
    "name": "SCL-90 症状自评量表",
    "description": "以下列出了有些人可能会有的问题，请仔细阅读每一条，根据最近一周的实际感觉，选择最符合的选项。总分范围90-450分，包括躯体化、强迫、人际敏感、抑郁、焦虑、敌对、恐怖、偏执、精神病性等9个因子。总分>=290或任意条目为5分时，建议寻求专业帮助。",
    "questions": [
        {"id": 1, "text": "头痛"},
        {"id": 2, "text": "神经过敏，心中不踏实"},
        {"id": 3, "text": "头脑中有不必要的想法或字句盘旋"},
        {"id": 4, "text": "头昏或昏倒"},
        {"id": 5, "text": "对异性的兴趣减退"},
        {"id": 6, "text": "对旁人责备求全"},
        {"id": 7, "text": "感到别人能控制你的思想"},
        {"id": 8, "text": "责怪别人制造麻烦"},
        {"id": 9, "text": "忘性大"},
        {"id": 10, "text": "担心自己的衣饰整齐及仪态的端正"},
        {"id": 11, "text": "容易烦恼和激动"},
        {"id": 12, "text": "胸痛"},
        {"id": 13, "text": "害怕空旷的场所或街道"},
        {"id": 14, "text": "感到自己的精力下降，活动减慢"},
        {"id": 15, "text": "想结束自己的生命"},
        {"id": 16, "text": "听到旁人听不到的声音"},
        {"id": 17, "text": "发抖"},
        {"id": 18, "text": "感到大多数人都不可信任"},
        {"id": 19, "text": "胃口不好"},
        {"id": 20, "text": "容易哭泣"},
        {"id": 21, "text": "同异性相处时感到害羞不自在"},
        {"id": 22, "text": "感到受骗、中了圈套或有人想抓住你"},
        {"id": 23, "text": "无缘无故地突然感到害怕"},
        {"id": 24, "text": "自己不能控制地大发脾气"},
        {"id": 25, "text": "怕单独出门"},
        {"id": 26, "text": "经常责怪自己"},
        {"id": 27, "text": "腰痛"},
        {"id": 28, "text": "感到难以完成任务"},
        {"id": 29, "text": "感到孤独"},
        {"id": 30, "text": "感到苦闷"},
        {"id": 31, "text": "过分担忧"},
        {"id": 32, "text": "对事物不感兴趣"},
        {"id": 33, "text": "感到害怕"},
        {"id": 34, "text": "我的感情容易受到伤害"},
        {"id": 35, "text": "旁人能知道你的私下想法"},
        {"id": 36, "text": "感到别人不理解你、不同情你"},
        {"id": 37, "text": "感到人们对你不友好、不喜欢你"},
        {"id": 38, "text": "做事必须做得很慢以保证做得正确"},
        {"id": 39, "text": "心跳得很厉害"},
        {"id": 40, "text": "恶心或胃部不舒服"},
        {"id": 41, "text": "感到比不上他人"},
        {"id": 42, "text": "肌肉酸痛"},
        {"id": 43, "text": "感到有人在监视你、谈论你"},
        {"id": 44, "text": "难以入睡"},
        {"id": 45, "text": "做事必须反复检查"},
        {"id": 46, "text": "难以做出决定"},
        {"id": 47, "text": "怕乘电车、公共汽车、地铁或火车"},
        {"id": 48, "text": "呼吸有困难"},
        {"id": 49, "text": "一阵阵发冷或发热"},
        {"id": 50, "text": "因为感到害怕而避开某些东西、场合或活动"},
        {"id": 51, "text": "脑子变空了"},
        {"id": 52, "text": "身体发麻或刺痛"},
        {"id": 53, "text": "喉咙有梗塞感"},
        {"id": 54, "text": "感到前途没有希望"},
        {"id": 55, "text": "不能集中注意力"},
        {"id": 56, "text": "感到身体的某一部分软弱无力"},
        {"id": 57, "text": "感到紧张或容易紧张"},
        {"id": 58, "text": "感到手或脚发重"},
        {"id": 59, "text": "想到死亡的事"},
        {"id": 60, "text": "吃得太多"},
        {"id": 61, "text": "当别人看着你或谈论你时感到不自在"},
        {"id": 62, "text": "有一些不属于你自己的想法"},
        {"id": 63, "text": "有想打人或伤害他人的冲动"},
        {"id": 64, "text": "醒得太早"},
        {"id": 65, "text": "必须反复洗手、点数目或触摸某些东西"},
        {"id": 66, "text": "睡得不稳不深"},
        {"id": 67, "text": "有想摔坏或破坏东西的冲动"},
        {"id": 68, "text": "有一些别人没有的想法或念头"},
        {"id": 69, "text": "感到对别人神经过敏"},
        {"id": 70, "text": "在商店或电影院等人多的地方感到不自在"},
        {"id": 71, "text": "感到任何事情都很困难"},
        {"id": 72, "text": "一阵阵恐惧或惊恐"},
        {"id": 73, "text": "感到在公共场合吃东西很不舒服"},
        {"id": 74, "text": "经常与人争论"},
        {"id": 75, "text": "单独一人时神经很紧张"},
        {"id": 76, "text": "别人对你的成绩没有作出恰当的评价"},
        {"id": 77, "text": "即使和别人在一起也感到孤单"},
        {"id": 78, "text": "感到坐立不安心神不定"},
        {"id": 79, "text": "感到自己没有什么价值"},
        {"id": 80, "text": "感到熟悉的东西变成陌生或不像是真的"},
        {"id": 81, "text": "大叫或摔东西"},
        {"id": 82, "text": "害怕会在公共场合昏倒"},
        {"id": 83, "text": "感到别人想占你的便宜"},
        {"id": 84, "text": "为一些有关性的想法而很苦恼"},
        {"id": 85, "text": "你认为应该因为自己的过错而受到惩罚"},
        {"id": 86, "text": "感到要赶快把事情做完"},
        {"id": 87, "text": "感到自己的身体有严重问题"},
        {"id": 88, "text": "从未感到和其他人很亲近"},
        {"id": 89, "text": "感到自己有罪"},
        {"id": 90, "text": "感到自己的脑子有毛病"},
    ],
    "options": [
        {"value": 1, "label": "没有"},
        {"value": 2, "label": "很轻"},
        {"value": 3, "label": "中等"},
        {"value": 4, "label": "偏重"},
        {"value": 5, "label": "严重"},
    ],
    "scoring": {
        "ranges": [
            {"min": 90, "max": 159, "level": "none", "label": "心理健康状况良好"},
            {"min": 160, "max": 199, "level": "yellow", "label": "轻度心理不适"},
            {"min": 200, "max": 239, "level": "yellow", "label": "中度心理问题"},
            {"min": 240, "max": 289, "level": "yellow", "label": "中重度心理问题，建议关注"},
            {"min": 290, "max": 450, "level": "red", "label": "重度心理问题，强烈建议寻求专业帮助"},
        ],
        "high_risk_item": 15,
    },
}


def seed_scales(db: Session):
    for data in [PHQ9, GAD7, SCL90]:
        existing = db.query(Scale).filter(Scale.name == data["name"]).first()
        if existing:
            continue
        scale = Scale(
            name=data["name"],
            description=data["description"],
            questions_json=json.dumps(data["questions"], ensure_ascii=False),
            scoring_rules_json=json.dumps(
                {"options": data["options"], "scoring": data["scoring"]},
                ensure_ascii=False,
            ),
        )
        db.add(scale)
    db.commit()